cdm/models/__init__.py
# -*- coding: utf-8 -*-

from cdm import db


class ModelMixin(object):

    def __repr__(self):
        return unicode(self.__dict__)

    def save(self):
        """ Save instance to database.
        """
        db.session.add(self)
        db.session.commit()

    def delete(self):
        """ Delete instance.
        """
        db.session.delete(self)
        db.session.commit()

cdm/models/submission.py
# -*- coding: utf-8 -*-

from sqlalchemy_utils import ArrowType
from sqlalchemy import Column, Integer, String, Boolean
from cdm import db
from cdm.models import ModelMixin

__all__ = ('Repo',)


class Submission(db.Model, ModelMixin):
    __tablename__ = 'submission'

    id = Column(Integer, primary_key=True)
    title = Column(String(200))
    link = Column(String(200))
    created_on = Column(ArrowType)
    submitted = Column(Boolean, default=False)
    submitted_by = Column(String(200))


    def __init__(self, title, submitted_by, link, created_on):
        self.title = title
        self.created_on = created_on
        self.link = link
        self.submitted_by = submitted_by

    def __repr__(self):
        return self.title

cdm/forms/forms.py
from flask.ext.wtf import Form
from wtforms import TextField, validators
from wtforms.validators import InputRequired


class RedditPostForm(Form):
    """Form to submit daily inspiration on /r/chadev..."""

    title = TextField(label=u'Title', validators=[InputRequired()])
    link = TextField(label=u'Link', validators=[InputRequired()])
    submitted_by = TextField(label=u'Submitted By', validators=[InputRequired()])

cdm/__init__.py
# -*- coding: utf-8 -*-

from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from config import config


app = Flask(__name__)
app.secret_key = config.APP_SECRET_KEY
app.config['PROPAGATE_EXCEPTIONS'] = True
app.config['SQLALCHEMY_DATABASE_URI'] = config.DATABASE_URI
app.debug = config.DEBUG

db = SQLAlchemy(app)

# custom jinja line delimeters
app.jinja_env.line_statement_prefix = '%'
app.jinja_env.line_comment_prefix = '##'

# register views
from cdm.views import general
app.register_blueprint(general.mod)

cdm/views/general.py
# -*- coding: utf-8 -*-

import os
import arrow
import hmac
import hashlib
import subprocess
from flask import Blueprint, render_template, flash
from flask import Flask, request
from cdm.forms.forms import RedditPostForm
from cdm.models.submission import Submission
from cdm import db

mod = Blueprint('general', __name__)


@mod.app_errorhandler(404)
def not_found_error(error):
    return render_template('404.html'), 404


@mod.app_errorhandler(500)
def internal_error(error):
    db.session.rollback()
    return render_template('500.html'), 500


@mod.route('/', methods=['POST', 'GET'])
def index():
    """Landing page."""
    form = RedditPostForm()
    if form.validate_on_submit():
        title = form.title.data
        link = form.link.data
        submitted_by = form.submitted_by.data
        if link_in_db(link):
            flash(
                u'This link has already been submitted, please submit another', 'danger')
            return render_template('index.html', form=form)
        save_to_db(title, link, submitted_by)
        flash(u'Your information has been submitted and will be posted to reddit soon. Thank you.', 'success')
        return render_template('success.html')

    return render_template('index.html', form=form)


@mod.route('/about', methods=['GET'])
def about():
    """About page."""
    return render_template('about.html')


@mod.route('/queue', methods=['GET'])
def queue():
    """List links and titles that are waiting to be submitted to reddit."""
    queue = Submission.query.filter_by(submitted=False).order_by(Submission.created_on)

    return render_template('queue.html', queue=queue)


@mod.route('/reddit_callback')
def reddit_callback():
    from flask import abort, request
    error = request.args.get('error', '')
    if error:
        return "Error: " + error
    state = request.args.get('state', '')
    if not is_valid_state(state):
        abort(403)
    code = request.args.get('code')
    return "got a code! %s" % code

@mod.route("/payload", methods=['POST'])
def github_payload():
    signature = request.headers.get('X-Hub-Signature')
    data = request.data
    if verify_hmac_hash(data, signature):
        if request.headers.get('X-GitHub-Event') == "ping":
            return jsonify({'msg': 'Ok'})
        if request.headers.get('X-GitHub-Event') == "push":
            payload = request.get_json()
            if payload['commits'][0]['distinct'] == True:
                try:
                    cmd_output = subprocess.check_output(
                        ['git', 'pull', 'origin', 'master'],)
                    cmd_output = cmd_output + subprocess.check_output(
                        ['sudo', 'supervisorctl', 'restart', 'gunicorn'],)

                    return jsonify({'msg': str(cmd_output)})
                except subprocess.CalledProcessError as error:
                    return jsonify({'msg': str(error.output)})

    else:
        return jsonify({'msg': 'invalid hash'})


def verify_hmac_hash(data, signature):
    github_secret = config.GITHUB_SECRET
    mac = hmac.new(github_secret, msg=data, digestmod=hashlib.sha1)
    return ('sha1='+mac.hexdigest()) == signature


def link_in_db(link):
    """Check if a link is in the db."""

    query = Submission.query.filter_by(link=link).first()
    if query:
        return True
    return False


def save_to_db(title, link, submitted_by):
    """Save title and link to db if it doesn't already exists."""

    utc = arrow.utcnow()
    est = utc.to('US/Eastern')
    submission = Submission(title=title, link=link, submitted_by=submitted_by, created_on=est)
    db.session.add(submission)
    db.session.commit()

config/__init__.py
# -*- coding: utf-8 -*-

import os
import config
from cdm.errors import ConfigVarNotFoundError
"""Set up config variables.

If environment variable ENVIRONMENT is set to dev and the config/dev.py
file exists then use that file as config settings, otherwise pull in settings from the production environment
"""

if os.environ.get('ENVIRONMENT') == 'dev':
    try:
        import dev as config  # config/dev.py
    except:
        raise EnvironmentError('Please create config/dev.py')
else:
    # production server environment variables
    basedir = os.path.abspath(os.path.join(os.path.dirname( __file__ ), os.pardir))
    config.APP_SECRET_KEY = os.environ.get('APP_SECRET_KEY')
    config.DEBUG = False
    config.DATABASE_URI = 'sqlite:///' + os.path.join(basedir, 'dev.db')
    config.CLIENT_ID = os.environ.get('CLIENT_ID')
    config.PORT = os.environ.get('PORT')
    config.CLIENT_SECRET = os.environ.get('CLIENT_SECRET')
    config.REDDIT_USERNAME = os.environ.get('REDDIT_USERNAME')
    config.REDDIT_PASSWORD = os.environ.get('REDDIT_PASSWORD')


try:
    config_vars = [config.APP_SECRET_KEY, config.DATABASE_URI,
                   config.CLIENT_ID, config.CLIENT_SECRET,
                   config.REDDIT_USERNAME, config.REDDIT_PASSWORD]
    any(config_vars) is None
except Exception, e:
    missing_var = e.message.split()[-1]
    raise ConfigVarNotFoundError(missing_var)

cdm/templates/about.html
% extends "base.html"
% block content
  <div>
    <h1>chaDevMonster<br>
    <small>"The /r/chadev subreddit bot"</small></h1>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h3>chaDevMonster's mission:</h3>
      <p>
        <ul>
          <li>save and store titles and links</li>
          <li>post one link to /r/chadev daily</li>
        </ul>
      </p>
    </div>
  </div>
% endblock

cdm/templates/base.html
% from "macros.html" import render_error
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link href="//cdn.muicss.com/mui-0.1.18/css/mui.min.css" rel="stylesheet" type="text/css" /> -->
    <script src="//cdn.muicss.com/mui-0.1.18/js/mui.min.js"></script>
    <link href="{{ url_for('static', filename='css/mui.min.css') }}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <style type="text/css">
      body{
        background-color: #535456;
        color: #929397;
      }
      .header{
        background-color: #FFFFFF;
        margin-bottom: 20px;
        height: 64px;
        padding-top: 5px;
      }
      #footer{
        background-color: #535456;
      }
      footer li a{
        color: #929397;
      }
      #container{
        min-height: 100%;
      }
      #logo{

      }

      /* Sticky footer styles
      -------------------------------------------------- */
      html,
      body {
        height: 100%;
        /* The html and body elements cannot have any padding or margin. */
      }

      /* Wrapper for page content to push down footer */
      #wrap {
        min-height: 100%;
        height: auto !important;
        height: 100%;
        /* Negative indent footer by it's height */
        margin: 0 auto -125px;
      }

      /* Set the fixed height of the footer here */
      #push,
      #footer {
        height: 125px;
        color: white;
        padding-top: 30px;
      }

      /* Lastly, apply responsive CSS fixes as necessary */
      @media (max-width: 767px) {
        #footer {
          margin-left: -20px;
          margin-right: -20px;
          padding-left: 20px;
          padding-right: 20px;
        }
      }
    </style>
  </head>
  <body>
    <div id="wrap">
      <header class="mui-appbar header">
        <div class="mui-container" id="logo">
          <a href="{{ url_for("general.index") }}"><img src="{{ url_for('static', filename='images/logo.svg') }}"/></a>
        </div>
      </header>
      <div class="mui-container">
        <div class="mui-panel">
          {{ render_error() }}
          % block content
          % endblock
        </div>
      </div>
      <div id="push"></div>
    </div>
    <footer id="footer">
      <hr>
      <div class="mui-container">
        <ul class="mui-list-inline">
          <li><a href="{{ url_for("general.about") }}">About</a></li>
          <li><a href="{{ url_for("general.queue") }}">Queue</a></li>
          <li><a href="https://github.com/juzten/chaDevMonster">Repo</a></li>
        </ul>
      </div>
    </footer>
  </body>
</html>

cdm/templates/index.html
% extends "base.html"
% block content
% from "macros.html" import render_field, render_checkbox_field, checkbox_with_errors

  <div>
    <h3>Submit interesting articles to be posted on <a href="https://www.reddit.com/r/chadev/">Chadev's subreddit</a><br>
    <small>
      Submissions are pulled and posted once a day
    </small>
    </h3>
    <br>
  </div>

  <form action="" method="post" name="issueform">
    {{ form.hidden_tag() }}
    {{ render_field(form.title, 'Title', style='mui-form-control') }}
    {{ render_field(form.link, 'Link', style='mui-form-control') }}
    {{ render_field(form.submitted_by, 'Submitted By', style='mui-form-control') }}
    <br>
    <div>
      <button type="submit" id="submit-form" class="mui-btn mui-btn-primary mui-btn-raised">
        Submit
      </button>
    </div>
  </form>
% endblock

cdm/templates/macros.html
% macro render_field(field, placeholder=None, rows=None, style=None)
  <div class="form-group {% if field.errors %}has-error has-feedback{% endif %}{% if placeholder %} with-placeholder{% endif %}">
    {{ field.label(class="control-label") }}
    % if placeholder
      {{ field(class=style, placeholder=placeholder, rows=rows) }}
    % else
      {{ field(class=style, rows=rows) }}
    % endif
    % if field.errors
      <ul class="errors">
      % for error in field.errors
        <li>
          <i class="fa fa-times form-feedback"></i>
          <span style="color: red;"> {{ error }}</span>
        </li>
      % endfor
      </ul>
    % else
      <p class="help-block">{{ field.description }}</p>
    % endif
  </div>
% endmacro

% macro render_error()
  % with messages = get_flashed_messages(with_categories=true)
    % if messages
      % for category, message in messages
      <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
      % endfor
    % endif
  % endwith
% endmacro

% macro render_checkbox_field(field, placeholder=None, rows=None, name='')
  <div class="form-group {% if field.errors %}has-error has-feedback{% endif %}{% if placeholder %} with-placeholder{% endif %}">
    {{ field.label(class="control-label") }}
    <div class="well" style="max-height: 300px;overflow: auto;">
      {# <ul class="list-group checked-list-box"> #}
      <ul>
      % for f in field
        {# <li class="list-group-item" style="cursor: pointer;"> #}
                <li style="cursor: pointer;">

          <span class="state-icon glyphicon glyphicon-unchecked"></span>
          <label for="labels-2">{{ f.label }}</label>
          {# <input type="checkbox" class="hidden" name={{ name }}> #}
          <input type="checkbox" name={{ name }}>
        </li>
      % endfor
      </ul>
      % if field.errors
        <ul class="errors">
        % for error in field.errors
          <li>
            <i class="fa fa-times form-feedback"></i>
            <span style="color: red;"> {{ error }}</span>
          </li>
        % endfor
        </ul>
      % else
        <p class="help-block">{{ field.description }}</p>
      % endif
    </div>
  </div>
% endmacro

% macro checkbox_with_errors(field, checked=False)
  <div class="form-group {% if field.errors %}has-error{% endif %}">
    <label class="checkbox-inline">
      {{ field(class="checkbox", checked=checked) }} {{ field.label }}
    </label>
    % if field.errors
      % for err in field.errors
        <p class="help-block">{{ err|safe }}</p>
      % endfor
    % else
      <p class="help-block">{{ field.description }}</p>
    % endif
  </div>
% endmacro

cdm/templates/queue.html
% extends "base.html"
% block content
  % if queue
  <h3>The following links are in queue for submission to /r/chadev</h3>

    <table class="mui-table mui-table-bordered">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Link</th>
        </tr>
      </thead>
      <tbody>
        % for item in queue
        <tr>
          <td>{{ loop.index }}</td>
          <td>{{ item.title }}</td>
          <td>{{ item.link }}</td>
        </tr>
        % endfor
       </tbody>
    </table>
  % endif
% endblock

cdm/templates/success.html
% extends "base.html"
% block content
<div>
    <br><br>
    If you want to view more information about the Chadev Monster <a href="{{ url_for("general.about") }}">click here</a>
    <br>
</div>
% endblock